Conect to api
uwadonat/bookstore pull request #3
Opened 2021-09-02 08:05 UTC by uwadonat

### Bookstore: connect to API

**In this milestone I implemented followings:**
- Refactor add book and remove book features to persist my changes in the server.
- Use middleware to make async requests to the API.
- Connect application with API and run in the browser.

**Hope to meet all requirements in this milestone**

_Thank you for your time to review my project_

2021-09-02 08:35 UTC, dasileker requested changes
### **Hi @uwadonat** 

Good job so far!
You have done a great job on this Milestone, but let's make this code great see the require changes down in inline comments.♻


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-02 08:35 UTC, dasileker commented on src/redux/books/books.js
> +}
- [ ] Let's make a good JS by using ES6 arrow functions. and async and await too

2021-09-02 08:35 UTC, dasileker commented on src/components/appComponents/booksComponents/AddBooForm.js
>            <option value="Sci-Fi">Sci-Fi</option>
- [ ] You can create a component for the form and callback the props to make it more clean.

2021-09-02 08:35 UTC, dasileker commented on src/components/appComponents/booksComponents/bookListComponents/BookItem.js
> +    <div className="book-item">
- [ ] You can use also this in separate component and add the filter to your reducer to make it clean.

2021-09-02 08:35 UTC, dasileker commented on src/redux/books/books.js
> +        progress: 74,
- [ ] The keys & values for the **bookObject** ca be placed in the **defaultState** instead.

2021-09-02 08:35 UTC, dasileker commented on src/redux/books/books.js
> +        progress: 74,
- [ ] Also the progress

2021-09-03 09:38 UTC, uwadonat commented on src/redux/books/books.js
> +        progress: 74,
thank you.

2021-09-03 10:19 UTC, uwadonat commented on src/redux/books/books.js
> +        progress: 74,
requested changes is done.

2021-09-03 10:42 UTC, DeliceLydia approved these changes
# Congratulations🎉 🎉 

## Hi @uwadonat, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-03 10:46 UTC, merged